[package]
name = "shallow-stone"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytemuck = { version = "1.21.0", features = ["derive"] }
glam = { version = "0.29.2", features = ["bytemuck"] }
pollster = "0.4.0"
wgpu = "23.0.1"
winit = "0.30.8"
